### ISSUE TITLE
Captured stdout and stderr.

### ISSUE THREAD

**Issue by rainwoodman** [bow/pytest-pipeline#1]
Hi,

We find it necessary to parse stdout and stderr of a pipeline piece. We currently open the saved files and read it in to parse. 

https://github.com/bccp/nbodykit/blob/master/nbodykit/test/asserts.py#L32
1. Could you comment if we are doing it right?
2. If so, it would be nicer if we can totally avoid using physical files for these. 
3. It is also nice if we can have 'joined' stdout and stderr. (like the -j eo flag of PBS/Torque).
4. Is there a way to automatically print the commandline and joined stdout/stderr in case of a failed test?

**Comment by rainwoodman** [comment]
Also cc-ing @nickhand

**Comment by bow** [comment]
Hi @rainwoodman,

1. That seems ok

2. That is indeed nicer. This would require the running test to communicate with the subprocess that runs the pipeline. The relevant function to be updated is [here](https://github.com/bow/pytest-pipeline/blob/master/pytest_pipeline/core.py#L47). One way (off the top of my head) is maybe to simply store the output in a StringIO object. But perhaps there are others. Any ideas / thoughts on this?

3. Yes, this would be nice as well :).

4. I'm not exactly sure, but I feel like there is a way to do this (need to look at the py.test API first to be sure).
